Feature/82 loading prompts db
bptlab/TracEX pull request #108
Opened 2024-04-21 15:45 UTC by soeren227

Closes #82 

**All prompts being used in the pipeline are now loaded from the database.**
- created prompts.json that can be loaded into database so there is no need to push the database
- all prompts are now loaded from the database
- adjustments to the Prompt model to make this possible
- added Prompt.category
- all prompts editable in admin view
- did not delete both of the prompts.py files yet, so reviewers can compare more easily

**Necessary steps for this to work (in TracEX\tracex_project):**
1. `python manage.py migrate`
2. `python manage.py loaddata prompts.json`

2024-04-22 09:04 UTC, thangixd approved these changes

2024-04-22 10:19 UTC, soeren227 commented on tracex_project/extraction/models.py
> +    DEFAULT_CATEGORY = "zero-shot"
because its the simplest prompting technique and if someone just quickly adds one prompt its most likely zero-shot

2024-04-22 10:19 UTC, soeren227 commented on tracex_project/extraction/models.py
> +    DEFAULT_CATEGORY = "zero-shot"
it also needed a default value

2024-04-22 14:09 UTC, tkv29 commented
@soeren227 reminder: you can load the prompt in the database and push the database, therefore the json can be deleted

2024-04-22 15:25 UTC, FR-SON requested changes

2024-04-22 16:26 UTC, soeren227 commented on tracex_project/extraction/logic/modules/module_trace_comparator.py
> +            # messages = p.COMPARE_MESSAGES[:]
nice catch

2024-04-23 08:00 UTC, tkv29 commented
![image](https://github.com/bptlab/TracEX/assets/73845255/64535cfa-5bfb-4831-9d89-5d68ec118031)
When generating a pj and selecting this one for the pipeline it crashes while extracting

2024-04-23 08:37 UTC, FR-SON commented
> I just checked the branch at I got errors cuz the db was cleared:D Did you also delete the 4 patient journey: journey_test_x and the related traces? These are important for the trace log comparator on main. Not sure we merge the db this db will replace the one on main or it will get merged ![image](https://private-user-images.githubusercontent.com/73845255/324750489-03330021-3779-47d1-bab6-ba5c3ce60751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjE2MTAsIm5iZiI6MTcxMzg2MTMxMCwicGF0aCI6Ii83Mzg0NTI1NS8zMjQ3NTA0ODktMDMzMzAwMjEtMzc3OS00N2QxLWJhYjYtYmE1YzNjZTYwNzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNjc1N2VmN2ZkZjQxMzQyM2U1ZWMwY2UyNGI0M2VhNDk5YmVlNjU4ZTVlMDk3OGNlYWIwYWNkNDVjMDI3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sysfApQjdmgJTo8riTw-Nm8-7J28fVcYgnmTg3GtA6c)

I tried to reproduce this problem but was not successful. When did this problem come up on your end?

2024-04-23 09:46 UTC, soeren227 commented
@tkv29 @FR-SON 
I can't reproduce your problem aswell Kien.
You can check which files i deleted in the PR history, and all other changes are already on main.
The db contains only the prompts. I can add other entries if you wish.
Maybe PM me and we can go through your concerns together on Discord.

2024-04-23 11:31 UTC, merged