Feature/66 choose pj from db
bptlab/TracEX pull request #115
Opened 2024-04-26 09:24 UTC by nils-schmitt

With this new feature you can now choose to extract a trace from the database.

2024-04-26 14:25 UTC, thangixd commented
![image](https://github.com/bptlab/TracEX/assets/105175491/19b03072-12bb-4b6a-9984-b31573308b94)

I migrated the db and I still get this error. Do I have to to something else? Is this only on my side? Please let me know @FR-SON @nils-schmitt

2024-04-26 14:32 UTC, thangixd commented
Why do we decide to automatically upload every patient journey to our database? But we need to decide if we want to save all tracers? Will there also be a possibility for the user to delete a patient journey in our app?

2024-04-26 15:34 UTC, nils-schmitt commented
> I still get the errors (see above). But good job guys!
> 
> Why do we decide to automatically upload every patient journey to our database? But we need to decide if we want to save all tracers in our db?
> 
> And will there also be a possibility for the user to delete a patient journey in our app?

Well there is already the possibility with the /admin view. And we save them, as this changes nothing and can easily be reverted. To delete a whole trace from the db is a little more tideous

2024-04-28 20:15 UTC, tkv29 commented
PO Review✅ gj!

2024-04-29 18:14 UTC, tkv29 commented
@PitButtchereit looking good!

2024-05-01 15:02 UTC, thangixd commented
![image](https://github.com/bptlab/TracEX/assets/105175491/6dbe9f57-66e5-46d3-8aac-bfe0d6641de4)

Can we perhaps achieve a better user experience if we don't have the same text twice in a row on the pages? How the filtering works is not yet relevant for the user here.

There should be another infobox instead of "The extraction pipeline helps you extract XES Event Logs from Patient Journeys. You can filter the results by event type and location before and after extraction to get exactly what you need."

something like: 

[....] You can either upload a patient journey or select an existing journey from the database.

2024-05-02 19:57 UTC, tkv29 requested changes

2024-05-02 19:57 UTC, tkv29 commented on tracex_project/extraction/templates/choose_input_method.html
> +            <a href='{% url 'journey_upload' %}'>
u have to use " instead of ' 

see below in code for correct way: "{% url 'landing_page' %}"

2024-05-03 09:36 UTC, soeren227 commented
When extracting the twice from the same journey and trying to save both results to the db i get the following error:
![image](https://github.com/bptlab/TracEX/assets/93621438/f0af6904-483b-4c98-8a29-c5f7155c3cfe)

2024-05-03 10:20 UTC, soeren227 requested changes
Everything looks good and well written. Apart from the capitalization comment (which is more a pointer than a mandatory change requirement), my biggest concern is that I can not extract from the same journey twice and save the result to the db a second time. This produces a key error. Maybe this falls out of the scope of your user story in which case i can approve the PR.

![image](https://github.com/bptlab/TracEX/assets/93621438/f0212b36-fd27-4ebc-b17f-03325fa36830)

2024-05-03 10:20 UTC, soeren227 commented on tracex_project/extraction/templates/select_journey.html
Capitalization sometimes seems a bit random. E.g at some point database is written with capital D and sometimes not. Same goes for patient journey/Patient Journey. Maybe we should try to make this uniform in later refactoring steps.

2024-05-03 11:15 UTC, PitButtchereit commented on tracex_project/extraction/templates/select_journey.html
If you are only talking about the select_journey.html then in my opinion it is fine since the "Select Patient Journey from Database" is a heading that gives the webpage a title when looking at it. The other is a descriptive text in english and hence subjects are written in lower case.

2024-05-03 12:20 UTC, PitButtchereit commented
@soeren227 I can not reproduce your error. Please show me on your machine.

2024-05-03 12:33 UTC, thangixd approved these changes

2024-05-03 13:40 UTC, soeren227 approved these changes
Looks good and everything works for me 👍

2024-05-03 16:34 UTC, merged