Feature/32 dataframe framework
bptlab/TracEX pull request #50
Opened 2024-01-18 09:05 UTC by nils-schmitt

Working implementation of the dataframe framework.

Please note, that output_handling is removed due to handling issues of dataframe / the csv file.

2024-01-18 11:14 UTC, FR-SON requested changes
Looks very good overall. I didn't run it with the changes though, only read through the changes. There are some minor improvements that should be made. 
It might be beneficial to document the insights you had that led to the changed prompts, as we will probably work on that topic further in the future.

2024-01-18 11:14 UTC, FR-SON commented on tracex/extraction/prototype/utils.py
> +#     return output
Is this still required? Otherwise, please remove.

2024-01-19 09:36 UTC, nils-schmitt commented on tracex/extraction/prototype/input_handling.py
> +    i = 0
The i was solely for debugging purposes, it is now removed completely

2024-01-22 08:24 UTC, PitButtchereit requested changes
Please implement some minor changes.

Also I am not sure about the idea to write the dataframe to a file after each pipeline step. What was your motivation about this?

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/input_handling.py
> +def farewell():
This is not necessary

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/input_handling.py
> +    bulletpoints = bulletpoints.replace("- ", "")
Have you tried to specify in the prompt that the activity labels should be in a specific output format? Then we would not have to do this formatting stuff.

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/prompts.py
> +    country = client.chat.completions.create(
this variable should not be named "country" as this is the function to get a random date

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/prompts.py
> +    You are an expert in text understanding and your job is to take a given text and a given bulletpoint and to extract a start date to this bulletpoint.
Please change the word bulletpoint to something else like event information

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/prompts.py
> +    Here is the text and the bulletpoint for which you should extract the start date in the format YYYYMMDD with the postfix T0000!
Same as above

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/prompts.py
In many prompts we still use the word "bulletpoint". Would be nice to change this

2024-01-22 08:24 UTC, PitButtchereit commented on tracex/extraction/prototype/input_handling.py
> +def add_durations(df):
I thought we would leave out durations for now

2024-01-30 12:24 UTC, PitButtchereit approved these changes
Joop Joop

2024-01-30 12:29 UTC, thangixd approved these changes
looks good to me. Good work

2024-01-30 12:39 UTC, FR-SON approved these changes

2024-01-30 12:40 UTC, merged