Refactor/40 implement architecture by refactoring code into classes
bptlab/TracEX pull request #52
Opened 2024-01-31 17:59 UTC by FR-SON

This PR changes the basic structure of the project by introducing a more modular architecture featuring an orchestrator, that manages separate modules, each of which is responsible for one dedicated step in the pipeline.
Modules can now easily be added or replaced by following theses steps
1. Create a class derived from the `Module` class from `module.py`
2. import the class in `orchestrator.py`
3. Make the required changes to the dictionary `modules` in the `ExtractionConfiguration` class (adding, removing)
4. Make the same changes to the list in `initialize_modules()` in the `orchestrator` class
5. Keep in mind, that modules can depend on each other and choose the order accordingly

Currently there are two modules for extracting timestamps. Pick whichever you prefer and follow the steps above to use the chose module.

This closes #40.

2024-02-06 09:36 UTC, nils-schmitt requested changes

2024-02-06 09:36 UTC, nils-schmitt commented on requirements.txt
> +pandas
```suggestion

```

2024-02-06 09:36 UTC, nils-schmitt commented on tracex/extraction/logic/__init__.py
> +"""Contains all the logic for the extraction process."""
```suggestion

```

2024-02-06 09:36 UTC, nils-schmitt commented on tracex/extraction/logic/modules/__init__.py
> +"""All modules used for the extraction, derived from the Module class."""
```suggestion

```

2024-02-06 09:36 UTC, nils-schmitt commented on requirements.txt
> +pandas
the pandas import is included in the pm4py import

2024-02-06 09:36 UTC, nils-schmitt commented on tracex/extraction/prototype/pipeline_without_user_io.py
This file should be deleted

2024-02-06 11:23 UTC, tkv29 commented
As disscued I have 2 suggestions:
1. Currently the orchestrator is initialized before the necessary config is created, therefore the config/instance variables of the orchestrator are none. Suggestion would be to initialize the orchestrator when a conifg is available and not before the config is created, so we only have an instance when needed.
2. Currently the orchestrator is directly accessing the results of the modules. I would suggest to implement a request return pattern, so the module will repsonse to the orchestrator with the results instead.

2024-02-09 14:30 UTC, FR-SON commented on tracex/extraction/prototype/pipeline_without_user_io.py
Done

2024-02-09 14:37 UTC, FR-SON commented
> As disscued I have 2 suggestions:
> 
>     1. Currently the orchestrator is initialized before the necessary config is created, therefore the config/instance variables of the orchestrator are none. Suggestion would be to initialize the orchestrator when a conifg is available and not before the config is created, so we only have an instance when needed.
> 
>     2. Currently the orchestrator is directly accessing the results of the modules. I would suggest to implement a request return pattern, so the module will repsonse to the orchestrator with the results instead.

The second suggestion is applied. The modules now return their results instead of saving them in instance variables. 
The first suggestion, though reasonable, can hopefully be postponed, as it requires considerable effort. I suggest to merge the discussed branch and work on the life-cycle management of the orchestrator on a separate branch so everyone can use the updated architecture asap. Thoughts on that?

2024-02-11 14:39 UTC, nils-schmitt approved these changes
Looks great, nice job!

Regarding the previous comment from Frederic, i agree on updating the architecture first and then manage the orchestrator seperately.

2024-02-14 20:49 UTC, tkv29 approved these changes
lgtm, as mentioned above the changes will be delievered separately

2024-02-19 08:48 UTC, merged