Feature/53 integrating database into tracex
bptlab/TracEX pull request #62
Opened 2024-03-19 11:29 UTC by FR-SON

This PR adds the database integration for TracEX. Uploaded patient journeys and all extraction results are saved. 
After seeing the extraction results, users can decide whether to save or discard them. 
There are some issues remaining (listed below). Feel free to comment on them, suggest solutions, implement them yourself or create issues to work on in the future.
As it stands now, everything works as intended, which is why I create this PR now, despite the known issues. Nevertheless, I understand if we only merge once at least issue 2 is resolved.
Please checkout the branch and really test the pipeline when reviewing. I worked on my own for a long time, so some things might now work on a different device, that I might not have noticed.
This closes #53.

### Issues:
1. Because some functions (e.g. the test mode for the UI) still rely on csv/xes files, these files are still written to disk. In a future update, all these functions need to be adapted to use database queries instead of reading files.
2. When users decide to discard the extraction results, the `Cohort` will still remain in the database, because it is always saved once extracted. This will affect all results, that have a relationship to the extracted `Trace`, right now `Cohort` is the only one implemented.
3. The names of patient journeys are unique, but it is not yet possible for users to choose a previously uploaded patient journey to extract from.

### Possible Solutions:
1. Add the necessary entries to the database and push it. From then on, the database file should not be included in commits.
2. Change the `execute_and_save()` method to return a dictionary instead. Then the `Orchestrator` can handle saving the model instances all together – if the user wishes to do so. (Django can create model instances directly from dictionaries.). 
3. Create a new view, complementary to the `JourneyInputView` in which all available patient journeys in the database are displayed.

2024-03-19 12:09 UTC, nils-schmitt commented
It would be good to either automate the update of the db or include the update steps in the README

2024-03-19 13:59 UTC, nils-schmitt requested changes
Looks good so far, I would like to add onto the known issues, that only activities with retrieved eventtypes and location are shown in the result view. (But that should be tackled as an individual issue)

2024-03-19 13:59 UTC, nils-schmitt commented on tracex/extraction/migrations/0005_alter_trace_managers_remove_trace_duration_and_more.py
"and_more" seems like an odd name?

2024-03-19 14:02 UTC, FR-SON commented on tracex/extraction/migrations/0005_alter_trace_managers_remove_trace_duration_and_more.py
These files are automatically generated when running `manage.py makemigrations`, though i agree - it's an odd name :D

2024-03-19 14:02 UTC, FR-SON commented on tracex/extraction/migrations/0005_alter_trace_managers_remove_trace_duration_and_more.py
Good point, I will update the README

2024-03-19 14:03 UTC, FR-SON commented
> It would be good to either automate the update of the db or include the update steps in the README.
> 
> EDIT: You should also note, that if no executionpath is set, the command needs to be `python tracex/manage.py [...]` to run it from the root directory.

Good point, I will update the README

2024-03-19 14:04 UTC, nils-schmitt commented on tracex/extraction/migrations/0005_alter_trace_managers_remove_trace_duration_and_more.py
Okay, nevermind then

2024-03-19 14:05 UTC, nils-schmitt approved these changes

2024-03-20 09:04 UTC, tkv29 requested changes

2024-03-21 23:04 UTC, tkv29 approved these changes

2024-03-22 08:28 UTC, merged